### ISSUE TITLE
EVIDENZIATRE

### ISSUE THREAD

**Issue by Gusso0o** [Cutotopo/inkpaint#1]
HO FINITO DI EVIDENZIARE E NON SI PUO' PIU TOGLIERE 
RISOLVETE SUBITO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Cutotopo** [comment]
You should use the checkbox Tools > Highlighter... I'll fix this in the next update by adding a "disable highlighter" button in the ribbon backstage.

**Comment by Gusso0o** [comment]
Ti scrivo in italiano, mi rispondi in ialiano.
RISOLVETE SUBITO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Con amore,
Ciro Esposito

**Comment by Cutotopo** [comment]
If you want an answer in Italian, just go on the Italian repository (Cutotopo/inkpaint-it).

**Comment by Gusso0o** [comment]
Ok ma è scomodo

**Comment by Gusso0o** [comment]
Non va ancora
